data_ingestion_config:
  zip_file_name: PennFudanPed.zip
  bucket_name: custom-instance-segm

data_transformation_config:
  prob: 0.5

model_trainer_config:
  lr: 0.005
  epochs: 1
  gamma: 0.1
  step_size: 3
  momentum: 0.9
  test_batch: 1
  num_classes: 2
  train_batch: 2
  num_workers: 4
  hidden_layer: 256
  weight_decay: 0.0005

model_evaluation_config:
  batch_size: 1
  num_workers: 4
  bucket_name: custom-instance-segm

model_pusher_config:
  bucket_name: custom-instance-segm

prediction_pipeline_config:
  bucket_name: custom-instance-segm
  model_name: model.pt